#!/usr/bin/env bash
#  This bash script displays "To infinity and beyond" indefinitely with a
#+ sleep 2 in between each iterations and "I am invicible!!!" when receiving
#+ a SIGTERM signal

function sigterm_signal {
    echo "I am invicible!!!"
}

trap sigterm_signal SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
