#!/usr/bin/env bash
# Configures nginx
pkill apache2
sed -i 's/user\s*\(.*\);/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
