#!/usr/bin/env bash
# Bash script that creates an RSA key pair.
# Name of the created private key must be `school`
# Number of bits in the created key to be created `4096`

ssh-keygen -t rsa -b 4096 -P betty -f school
